---
- name: install yum repo
  template:
    owner=root
    src=docker.repo
    dest=/etc/yum.repos.d/docker.repo

- name: Install docker
  yum: name={{ item }} state=latest
  with_items:
    - docker-ce
    - python-docker-py

- name: configure Docker daemon with storage driver
  template:
    owner=root
    src=docker.conf
    dest=/usr/lib/systemd/system/docker.service

- name: configure Docker Daemon Web Socket
  template:
    owner=root
    src=docker.socket
    dest=/usr/lib/systemd/system/docker.socket

  notify:
    - reload units
    - restart docker
