---
- name: check if kernel upgrade is pending
  shell: if [[ "{{ ansible_kernel }}" =~ ^3. ]]; then echo "yes"; else echo "nope"; fi
  changed_when: no
  ignore_errors: yes
  register: must_upgrade_kernel

- name: tell grub to boot latest kernel by default
  shell: egrep ^menuentry /etc/grub2.cfg | cut -f 2 -d \' | head -1 | awk '{ print "grub2-set-default \"" $0 "\"" }' | sh
  when: must_upgrade_kernel.stdout == "yes"

- name: restart machine
  shell: shutdown -r now 
  async: 1
  poll: 0
  ignore_errors: yes
  when: must_upgrade_kernel.stdout == "yes"

- name: waiting for server to come back
  wait_for: >
    port=22
    host={{ ansible_host | default(inventory_hostname) }}
    delay=15
    timeout=600
  delegate_to: localhost
  when: must_upgrade_kernel.stdout == "yes"
